from pyspark.sql.types import StructType, StructField, StringType, DateType, IntegerType

exhib_schema = StructType( [StructField('ExhibitionID', IntegerType(), True),
                            StructField('ExhibitionNumber', StringType(), True),
                            StructField('ExhibitionTitle', StringType(), True),
                            StructField('ExhibitionCitationDate', StringType(), True),
                            StructField('ExhibitionBeginDate', DateType(), True),
                            StructField('ExhibitionEndDate', DateType(), True),
                            StructField('ExhibitionSortOrder', StringType(), True),
                            StructField('ExhibitionURL', StringType(), True),
                            StructField('ExhibitionRole', StringType(), True),
                            StructField('ExhibitionRoleinPressRelease', StringType(), True),
                            StructField('ConstituentID', StringType(), True),
                            StructField('ConstituentType', StringType(), True),
                            StructField('DisplayName', StringType(), True),
                            StructField('AlphaSort', StringType(), True),
                            StructField('FirstName', StringType(), True),
                            StructField('MiddleName', StringType(), True),
                            StructField('LastName', StringType(), True),
                            StructField('Suffix', StringType(), True),
                            StructField('Institution', StringType(), True),
                            StructField('Nationality', StringType(), True),
                            StructField('ConstituentBeginDate', IntegerType(), True),
                            StructField('ConstituentEndDate', IntegerType(), True),
                            StructField('ArtistBio', StringType(), True),
                            StructField('Gender', StringType(), True),
                            StructField('VIAFID', StringType(), True),
                            StructField('WikidataID', StringType(), True),
                            StructField('ULANID', StringType(), True),
                            StructField('ConstituentURL', StringType(), True)])
exhib_date_format = "M/d/yyyy"